places = ["Concepcion", "Valdivia", "Santiago", "Talca", "Pichilemu"]
print(sorted(places))
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
